CREATE USER AMAZON
  IDENTIFIED BY "oracle"
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP;
ALTER USER AMAZON QUOTA UNLIMITED ON USERS;

GRANT create session TO AMAZON;
GRANT create table TO AMAZON;
GRANT create view TO AMAZON;
GRANT create any trigger TO AMAZON;
GRANT create any procedure TO AMAZON;
GRANT create sequence TO AMAZON;
GRANT create synonym TO AMAZON;